# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04b7e81df0e8439324c997e7374fc81a367b2b34d74cbd30d09317ffeb65f4c890eb913fae425663c4c95fafec4503d971658e5bcb10901a6844f5ace2230491

test:
  secret_key_base: 81810da93734074d67723bc5f1e6a435452da7cff26eb7c530d54ecdf049f88eee7e0d97907ab48e21076838e573d8bc5f313cb893a60140dbc3d92ad70a0e47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
